# Configures rkt tests at Travis CI (https://travis-ci.org).

language: go

go:
  - 1.5.3

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y cpio realpath squashfs-tools
 - sudo apt-get install -y build-essential
 - sudo apt-get install -y libacl1-dev
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls

script:
 - ./autogen.sh
 # Build host and fly to ensure we build stage1 init. We don't build everything
 # to avoid downloading large images.
 - ./configure --with-stage1-flavors=host,fly
 - make unit-check
